// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptionsEngine.Infrastructure.Persistence;

#nullable disable

namespace OptionsEngine.Infrastructure.Migrations
{
    [DbContext(typeof(OptionsEngineDbContext))]
    [Migration("20260918170325_AddEntryStrategyEvaluations")]
    partial class AddEntryStrategyEvaluations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTaxDeferred")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Holding", b =>
                {
                    b.Property<Guid>("HoldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentSensitivity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaximumCoveragePercent")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<double>("MaximumDeltaExposureRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("MaximumInitialDelta")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumAnnualizedYield")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumCcos")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumContractScore")
                        .HasColumnType("REAL");

                    b.Property<decimal>("MinimumPremium")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<double>("PreferredDeltaMaximum")
                        .HasColumnType("REAL");

                    b.Property<double>("PreferredDeltaMinimum")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxSensitivity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("HoldingId");

                    b.HasIndex("AccountId", "Symbol");

                    b.ToTable("Holdings", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.TaxLot", b =>
                {
                    b.Property<Guid>("TaxLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AcquisitionDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostBasisPerShare")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HoldingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoldingPeriodClassification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCostBasis")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("TaxLotId");

                    b.HasIndex("HoldingId");

                    b.ToTable("TaxLots", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Infrastructure.Persistence.EmptyOptionChainSnapshotEntity", b =>
                {
                    b.Property<long>("EmptyOptionChainSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnderlyingSymbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("EmptyOptionChainSnapshotId");

                    b.HasIndex("UnderlyingSymbol", "Provider", "Expiration", "TimestampUtcTicks");

                    b.ToTable("EmptyOptionChainSnapshots", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Infrastructure.Persistence.EntryStrategyEvaluationEntity", b =>
                {
                    b.Property<Guid>("EntryStrategyEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CcosClassification")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CcosScore")
                        .HasColumnType("REAL");

                    b.Property<string>("CcosStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigurationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DispositionReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EntryCandidateExists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvaluationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EvaluationTimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HoldingId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IndicatorAsOfDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicatorCalculationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PreferredInitialExpiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredInitialOptionSymbol")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreferredInitialReferencePremium")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreferredInitialStrike")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("EntryStrategyEvaluationId");

                    b.HasIndex("Symbol");

                    b.HasIndex("HoldingId", "CalculatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("EntryStrategyEvaluations", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Infrastructure.Persistence.HistoricalPriceBarEntity", b =>
                {
                    b.Property<long>("HistoricalPriceBarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("HistoricalPriceBarId");

                    b.HasIndex("Symbol", "Date", "Provider")
                        .IsUnique();

                    b.HasIndex("Symbol", "Provider", "Date");

                    b.ToTable("HistoricalPriceBars", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Infrastructure.Persistence.HistoricalPriceCoverageEntity", b =>
                {
                    b.Property<long>("HistoricalPriceCoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("HistoricalPriceCoverageId");

                    b.HasIndex("Symbol", "Provider", "StartDate", "EndDate");

                    b.ToTable("HistoricalPriceCoverages", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Infrastructure.Persistence.IndicatorSnapshotEntity", b =>
                {
                    b.Property<long>("IndicatorSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigurationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndicatorCalculationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Iv30Value")
                        .HasColumnType("REAL");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("IndicatorSnapshotId");

                    b.HasIndex("Symbol", "AsOfDate", "IndicatorCalculationVersion", "ConfigurationVersion")
                        .IsUnique();

                    b.ToTable("IndicatorSnapshots", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Infrastructure.Persistence.MarketQuoteSnapshotEntity", b =>
                {
                    b.Property<long>("MarketQuoteSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Ask")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Bid")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDelayed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Last")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousClose")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("MarketQuoteSnapshotId");

                    b.HasIndex("Symbol", "Provider", "Timestamp");

                    b.ToTable("MarketQuoteSnapshots", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Infrastructure.Persistence.OptionContractSnapshotEntity", b =>
                {
                    b.Property<long>("OptionContractSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Ask")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Bid")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Delta")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Gamma")
                        .HasColumnType("REAL");

                    b.Property<double?>("ImpliedVolatility")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("Last")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OpenInterest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Strike")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Theta")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UnderlyingPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnderlyingSymbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Vega")
                        .HasColumnType("REAL");

                    b.Property<long?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("OptionContractSnapshotId");

                    b.HasIndex("OptionSymbol", "Provider", "Timestamp");

                    b.HasIndex("UnderlyingSymbol", "Provider", "Timestamp");

                    b.ToTable("OptionContractSnapshots", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Infrastructure.Persistence.OptionExpirationCacheEntity", b =>
                {
                    b.Property<long>("OptionExpirationCacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpirationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("OptionExpirationCacheId");

                    b.HasIndex("Symbol", "Provider", "RetrievedAt");

                    b.ToTable("OptionExpirationCaches", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Holding", b =>
                {
                    b.HasOne("OptionsEngine.Domain.Accounts.Account", "Account")
                        .WithMany("Holdings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.TaxLot", b =>
                {
                    b.HasOne("OptionsEngine.Domain.Accounts.Holding", "Holding")
                        .WithMany("TaxLots")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Holding", b =>
                {
                    b.Navigation("TaxLots");
                });
#pragma warning restore 612, 618
        }
    }
}
