// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptionsEngine.Infrastructure.Persistence;

#nullable disable

namespace OptionsEngine.Infrastructure.Migrations
{
    [DbContext(typeof(OptionsEngineDbContext))]
    partial class OptionsEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTaxDeferred")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Holding", b =>
                {
                    b.Property<Guid>("HoldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentSensitivity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaximumCoveragePercent")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<double>("MaximumDeltaExposureRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("MaximumInitialDelta")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumAnnualizedYield")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumCcos")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumContractScore")
                        .HasColumnType("REAL");

                    b.Property<decimal>("MinimumPremium")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<double>("PreferredDeltaMaximum")
                        .HasColumnType("REAL");

                    b.Property<double>("PreferredDeltaMinimum")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxSensitivity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("HoldingId");

                    b.HasIndex("AccountId", "Symbol");

                    b.ToTable("Holdings", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.TaxLot", b =>
                {
                    b.Property<Guid>("TaxLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AcquisitionDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostBasisPerShare")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HoldingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoldingPeriodClassification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCostBasis")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("TaxLotId");

                    b.HasIndex("HoldingId");

                    b.ToTable("TaxLots", (string)null);
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Holding", b =>
                {
                    b.HasOne("OptionsEngine.Domain.Accounts.Account", "Account")
                        .WithMany("Holdings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.TaxLot", b =>
                {
                    b.HasOne("OptionsEngine.Domain.Accounts.Holding", "Holding")
                        .WithMany("TaxLots")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("OptionsEngine.Domain.Accounts.Holding", b =>
                {
                    b.Navigation("TaxLots");
                });
#pragma warning restore 612, 618
        }
    }
}
